name: CrawlingExecutor build & test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'CrawlingExecutor/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn -B package --file pom.xml
        working-directory: CrawlingExecutor

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Crawling_SNAPSHOT.jar
          path: CrawlingExecutor/target/*.jar
